### ISSUE TITLE
Check-In List (List of PUDM Users)

### ISSUE THREAD

**Issue by marsha88** [for-each-org/PUDM-app#5]
### Goal:
Create component to display list of PUDM users signed up for event. This portion of the application will be used by PUDM Administrators to check people into the event.

The data received from the server will be of the form:
```
checkInList: [ {name: <String>, email: <String>, bag: <Bool>, checkIn: Boolean } ]
```

Please add sample data to the front-end until the server has successfully implemented endpoints.

Quick Mock Up: (Specific coloring doesn't matter. Styles will change later)
<img width="414" alt="screen shot 2018-03-03 at 1 57 44 pm" src="https://user-images.githubusercontent.com/14015552/36938108-eb1e59cc-1eea-11e8-802b-857160f51ed5.png">

For additional help go check out the NotificationsList.js file. The structure of the Notifications list is very similar to the Check-In list and will serve as a good example component.

**Comment by marsha88** [comment]
Current status: Uses identical styling to NotificationsList
<img width="316" alt="screen shot 2018-04-05 at 7 03 05 pm" src="https://user-images.githubusercontent.com/14015552/38396097-3a552740-3904-11e8-89b5-0ebe20f11b7c.png">

**Comment by drewatk** [comment]
Done in #14
